# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 17:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('mobile_number', models.IntegerField(default=None, null=True)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnid', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField(default=None, null=True)),
                ('number_of_adults', models.IntegerField(default=1)),
                ('number_of_children', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number_of_rooms', models.IntegerField(default=1)),
                ('checkin_date', models.DateField(default=datetime.date(2017, 3, 5))),
                ('checkout_date', models.DateField(default=datetime.date(2017, 3, 6))),
                ('room_type', models.CharField(choices=[(b'PS', b'Premium Single'), (b'PD', b'Premium Double'), (b'DD', b'Deluxe Double')], default=b'PS', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enquiry.Reservation'),
        ),
    ]
