# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_auto_20170305_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='txnid',
        ),
        migrations.AddField(
            model_name='reservation',
            name='txnid',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
