# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 18:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0003_auto_20170305_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='checkin_date',
            field=models.DateField(default=datetime.date(2017, 3, 6)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkout_date',
            field=models.DateField(default=datetime.date(2017, 3, 7)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='txnid',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
