# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_auto_20170306_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_of_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
